set echo on
spool monlib_output.txt

-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2131
--   at:        2018-04-23 13:42:36 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

/* Richard Osakwe 29466695*/


DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE book CASCADE CONSTRAINTS;

DROP TABLE book_availability CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE fine CASCADE CONSTRAINTS;

DROP TABLE identifier CASCADE CONSTRAINTS;

DROP TABLE library_branch CASCADE CONSTRAINTS;

DROP TABLE loans CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reservation CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

DROP TABLE title CASCADE CONSTRAINTS;

DROP TABLE title_author CASCADE CONSTRAINTS;

DROP TABLE title_subject CASCADE CONSTRAINTS;

DROP SEQUENCE auth_code_seq;

DROP SEQUENCE ava_code_seq;

DROP SEQUENCE bor_id_seq;

DROP SEQUENCE lib_code_seq;

DROP SEQUENCE man_code_seq;

DROP SEQUENCE pub_code_seq;

DROP SEQUENCE res_no_seq;

DROP SEQUENCE sub_code_seq;


CREATE TABLE author (
    auth_code        NUMBER NOT NULL,
    auth_firstname   VARCHAR2(50),
    auth_lastname    VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN author.auth_code IS
    'Author''s unique identifier';

COMMENT ON COLUMN author.auth_firstname IS
    'Author''s first name';

COMMENT ON COLUMN author.auth_lastname IS
    'Author''s last name. Authors with one name should be entered into here.';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( auth_code );

CREATE TABLE book (
    book_code      CHAR(14) NOT NULL,
    lib_code       NUMBER NOT NULL,
    isbn_code      VARCHAR2(13) NOT NULL,
    ava_code       NUMBER NOT NULL,
    title_callno   CHAR(20) NOT NULL
);

COMMENT ON COLUMN book.book_code IS
    'Book''s barcode';

COMMENT ON COLUMN book.lib_code IS
    'Library branch''s unique identifier. Sequence starts from 100.';

COMMENT ON COLUMN book.isbn_code IS
    'ISBN code ';

COMMENT ON COLUMN book.ava_code IS
    'Availability''s unique identifier';

COMMENT ON COLUMN book.title_callno IS
    'Title''s call number';

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( book_code );

CREATE TABLE book_availability (
    ava_code     NUMBER NOT NULL,
    ava_status   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN book_availability.ava_code IS
    'Availability''s unique identifier';

COMMENT ON COLUMN book_availability.ava_status IS
    'Book''s availability status';

ALTER TABLE book_availability ADD CONSTRAINT book_availability_pk PRIMARY KEY ( ava_code );

CREATE TABLE borrower (
    bor_id          NUMBER NOT NULL,
    bor_firstname   VARCHAR2(50),
    bor_lastname    VARCHAR2(50) NOT NULL,
    bor_status      CHAR(1) DEFAULT 'C' NOT NULL,
    bor_class       CHAR(1) NOT NULL,
    lib_code        NUMBER NOT NULL
);

ALTER TABLE borrower
    ADD CONSTRAINT chk_borstatus CHECK ( bor_status IN (
        'C',
        'F'
    ) );

ALTER TABLE borrower
    ADD CONSTRAINT chk_borclass CHECK ( bor_class IN (
        'A',
        'J',
        'O'
    ) );

COMMENT ON COLUMN borrower.bor_id IS
    'Borrower''s unique identifier';

COMMENT ON COLUMN borrower.bor_firstname IS
    'Borrower''s first name.';

COMMENT ON COLUMN borrower.bor_lastname IS
    'Borrower''s last name. Borrowers with one name should be entered here.';

COMMENT ON COLUMN borrower.bor_status IS
    'Borrower''s status flag. Either C for clean or F for flagged. Default value is C.';

COMMENT ON COLUMN borrower.bor_class IS
    'Borrower''s classification. J for Junior, A for Adult or O for Organization.';

COMMENT ON COLUMN borrower.lib_code IS
    'Library branch''s unique identifier. Sequence starts from 100.';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( bor_id );

CREATE TABLE fine (
    res_no         NUMBER NOT NULL,
    fine_amtdue    NUMBER NOT NULL,
    fine_paydate   DATE
);

COMMENT ON COLUMN fine.res_no IS
    'Reservation number. Surrogate Key';

COMMENT ON COLUMN fine.fine_amtdue IS
    'Amount due for fine.';

COMMENT ON COLUMN fine.fine_paydate IS
    'Payment date of fine';

ALTER TABLE fine ADD CONSTRAINT fine_pk PRIMARY KEY ( res_no );

CREATE TABLE identifier (
    isbn_code      VARCHAR2(13) NOT NULL,
    book_type      VARCHAR2(50) NOT NULL,
    title_callno   CHAR(20) NOT NULL
);

COMMENT ON COLUMN identifier.isbn_code IS
    'ISBN code ';

COMMENT ON COLUMN identifier.book_type IS
    'Book type. e.g. student edition, hardcover etc.';

COMMENT ON COLUMN identifier.title_callno IS
    'Title''s call number';

ALTER TABLE identifier ADD CONSTRAINT identifier_pk PRIMARY KEY ( isbn_code );

CREATE TABLE library_branch (
    lib_code      NUMBER NOT NULL,
    lib_name      VARCHAR2(100) NOT NULL,
    lib_address   VARCHAR2(100) NOT NULL,
    lib_phone     VARCHAR2(11) NOT NULL,
    man_code      NUMBER NOT NULL
);

COMMENT ON COLUMN library_branch.lib_code IS
    'Library branch''s unique identifier. Sequence starts from 100.';

COMMENT ON COLUMN library_branch.lib_name IS
    'Library branch''s name.';

COMMENT ON COLUMN library_branch.lib_address IS
    'Address of library branch';

COMMENT ON COLUMN library_branch.lib_phone IS
    'Phone number of library branch. ';

COMMENT ON COLUMN library_branch.man_code IS
    'Manager''s unique identifier';

ALTER TABLE library_branch ADD CONSTRAINT library_branch_pk PRIMARY KEY ( lib_code );

CREATE TABLE loans (
    res_no         NUMBER NOT NULL,
    loan_date      DATE NOT NULL,
    loan_duedate   DATE NOT NULL,
    loan_rtndate   DATE
);

COMMENT ON COLUMN loans.res_no IS
    'Reservation number. Surrogate Key';

COMMENT ON COLUMN loans.loan_date IS
    'Date loan was made';

COMMENT ON COLUMN loans.loan_duedate IS
    'Date loan is due';

COMMENT ON COLUMN loans.loan_rtndate IS
    'Loan''s return date';

ALTER TABLE loans ADD CONSTRAINT loans_pk PRIMARY KEY ( res_no );

CREATE TABLE manager (
    man_code        NUMBER NOT NULL,
    man_firstname   VARCHAR2(50),
    man_lastname    VARCHAR2(50) NOT NULL,
    lib_code        NUMBER NOT NULL
);

COMMENT ON COLUMN manager.man_code IS
    'Manager''s unique identifier';

COMMENT ON COLUMN manager.man_firstname IS
    'Manager''s first name';

COMMENT ON COLUMN manager.man_lastname IS
    'Manager''s last name. Managers with one name should enter value here.';

COMMENT ON COLUMN manager.lib_code IS
    'Library branch''s unique identifier. Sequence starts from 100.';

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( man_code );

CREATE TABLE publisher (
    pub_code       NUMBER NOT NULL,
    pub_name       VARCHAR2(50) NOT NULL,
    pub_location   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN publisher.pub_code IS
    'Publisher''s unique identifier';

COMMENT ON COLUMN publisher.pub_name IS
    'Publisher''s name';

COMMENT ON COLUMN publisher.pub_location IS
    'Publisher''s location';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( pub_code );

CREATE TABLE reservation (
    res_no      NUMBER NOT NULL,
    res_date    DATE NOT NULL,
    bor_id      NUMBER NOT NULL,
    book_code   CHAR(14) NOT NULL
);

COMMENT ON COLUMN reservation.res_no IS
    'Reservation number. Surrogate Key';

COMMENT ON COLUMN reservation.bor_id IS
    'Borrower''s unique identifier';

COMMENT ON COLUMN reservation.book_code IS
    'Book''s barcode';

ALTER TABLE reservation ADD CONSTRAINT reservation_pk PRIMARY KEY ( res_no );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_bor_res_book_un UNIQUE ( bor_id,
    res_date,
    book_code );

CREATE TABLE subject (
    sub_code   NUMBER NOT NULL,
    sub_name   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN subject.sub_code IS
    'Suject''s unique identifier';

COMMENT ON COLUMN subject.sub_name IS
    'Name of subject';

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( sub_code );

CREATE TABLE title (
    title_callno        CHAR(20) NOT NULL,
    title_title         VARCHAR2(50) NOT NULL,
    title_descript      VARCHAR2(1000) NOT NULL,
    title_pubyear       DATE NOT NULL,
    title_pageno        VARCHAR2(10000) NOT NULL,
    title_class         CHAR(1) NOT NULL,
    title_readability   NUMBER,
    title_price         NUMBER NOT NULL,
    pub_code            NUMBER NOT NULL
);

ALTER TABLE title
    ADD CONSTRAINT chk_title_class CHECK ( title_class IN (
        'F',
        'R'
    ) );

ALTER TABLE TITLE ADD constraint chk_title_readability CHECK ( title_readability > 0 AND <= 30);
COMMENT ON COLUMN title.title_callno IS
    'Title''s call number';

COMMENT ON COLUMN title.title_title IS
    'Title of book';

COMMENT ON COLUMN title.title_descript IS
    'Description of title';

COMMENT ON COLUMN title.title_pubyear IS
    'Title''s publication year';

COMMENT ON COLUMN title.title_pageno IS
    'Number of pages in title.';

COMMENT ON COLUMN title.title_class IS
    'Title''s classification. F for fiction or R for reference.';

COMMENT ON COLUMN title.title_readability IS
    'Title readability. For fiction ranges from 1 to 30. For Reference leave Null.';

COMMENT ON COLUMN title.title_price IS
    'Title''s purchase price';

COMMENT ON COLUMN title.pub_code IS
    'Publisher''s unique identifier';

ALTER TABLE title ADD CONSTRAINT title_pk PRIMARY KEY ( title_callno );

CREATE TABLE title_author (
    auth_code      NUMBER NOT NULL,
    title_callno   CHAR(20) NOT NULL
);

COMMENT ON COLUMN title_author.auth_code IS
    'Author''s unique identifier';

COMMENT ON COLUMN title_author.title_callno IS
    'Title''s call number';

ALTER TABLE title_author ADD CONSTRAINT title_author_pk PRIMARY KEY ( auth_code,
title_callno );

CREATE TABLE title_subject (
    sub_code       NUMBER NOT NULL,
    title_callno   CHAR(20) NOT NULL
);

COMMENT ON COLUMN title_subject.sub_code IS
    'Suject''s unique identifier';

COMMENT ON COLUMN title_subject.title_callno IS
    'Title''s call number';

ALTER TABLE title_subject ADD CONSTRAINT title_subject_pk PRIMARY KEY ( title_callno,
sub_code );

ALTER TABLE book
    ADD CONSTRAINT book_book_availability_fk FOREIGN KEY ( ava_code )
        REFERENCES book_availability ( ava_code );

ALTER TABLE book
    ADD CONSTRAINT book_identifier_fk FOREIGN KEY ( isbn_code )
        REFERENCES identifier ( isbn_code );

ALTER TABLE book
    ADD CONSTRAINT book_library_branch_fk FOREIGN KEY ( lib_code )
        REFERENCES library_branch ( lib_code );

ALTER TABLE book
    ADD CONSTRAINT book_title_fk FOREIGN KEY ( title_callno )
        REFERENCES title ( title_callno );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_library_branch_fk FOREIGN KEY ( lib_code )
        REFERENCES library_branch ( lib_code );

ALTER TABLE fine
    ADD CONSTRAINT fine_loans_fk FOREIGN KEY ( res_no )
        REFERENCES loans ( res_no )
            ON DELETE CASCADE;

ALTER TABLE identifier
    ADD CONSTRAINT identifier_title_fk FOREIGN KEY ( title_callno )
        REFERENCES title ( title_callno );

ALTER TABLE library_branch
    ADD CONSTRAINT library_branch_manager_fk FOREIGN KEY ( man_code )
        REFERENCES manager ( man_code );

ALTER TABLE loans
    ADD CONSTRAINT loans_reservation_fk FOREIGN KEY ( res_no )
        REFERENCES reservation ( res_no )
            ON DELETE CASCADE;

ALTER TABLE manager
    ADD CONSTRAINT manager_library_branch_fk FOREIGN KEY ( lib_code )
        REFERENCES library_branch ( lib_code );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_book_fk FOREIGN KEY ( book_code )
        REFERENCES book ( book_code )
            ON DELETE CASCADE;

ALTER TABLE reservation
    ADD CONSTRAINT reservation_borrower_fk FOREIGN KEY ( bor_id )
        REFERENCES borrower ( bor_id )
            ON DELETE CASCADE;

ALTER TABLE title_author
    ADD CONSTRAINT title_author_author_fk FOREIGN KEY ( auth_code )
        REFERENCES author ( auth_code )
            ON DELETE CASCADE;

ALTER TABLE title_author
    ADD CONSTRAINT title_author_title_fk FOREIGN KEY ( title_callno )
        REFERENCES title ( title_callno );

ALTER TABLE title
    ADD CONSTRAINT title_publisher_fk FOREIGN KEY ( pub_code )
        REFERENCES publisher ( pub_code );

ALTER TABLE title_subject
    ADD CONSTRAINT title_subject_subject_fk FOREIGN KEY ( sub_code )
        REFERENCES subject ( sub_code )
            ON DELETE CASCADE;

ALTER TABLE title_subject
    ADD CONSTRAINT title_subject_title_fk FOREIGN KEY ( title_callno )
        REFERENCES title ( title_callno )
            ON DELETE CASCADE;

CREATE SEQUENCE auth_code_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE ava_code_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE bor_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE lib_code_seq START WITH 100 NOCACHE ORDER;

CREATE SEQUENCE man_code_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE pub_code_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE res_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE sub_code_seq START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             37
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          8
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
set echo off 
spool off
